### ISSUE TITLE
cant read Texture2D by 2020.3.13 f1 AssetBundle

### ISSUE THREAD

**Issue by CCTV-1** [K0lb3/UnityPy#77] opened 2021-12-11 09:15 UTC
Code:
```Python3
import UnityPy

env = UnityPy.load("demo.res")

for obj in env.objects:
    if obj.type.name == "Texture2D":
        objData = obj.read()

        pass
```

```
Traceback (most recent call last):
  File "C:\Users\***\demo.py", line 7, in <module>
    objData = obj.read()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\files\ObjectReader.py", line 155, in read
    raise e
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\files\ObjectReader.py", line 153, in read
    obj = getattr(classes, self.type.name, classes.Object)(self)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\UnityPy\classes\Texture2D.py", line 92, in __init__
    self.m_TextureFormat = TextureFormat(reader.read_int())
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\enum.py", line 385, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\enum.py", line 710, in __new__
    raise ve_exc
ValueError: 128 is not a valid TextureFormat
```

`Python 3.10 - Windows 64` and `Python 3.9.7 - Fedora`
UnityPy:`1.7.25`
Unity version: `2020.3.13 f1` [demo file zip](https://github.com/K0lb3/UnityPy/files/7696716/demo.zip)

[AssetStudio ](https://github.com/Perfare/AssetStudio)can read it(need manually specify Unity version). [UABEAvalonia](https://github.com/nesrak1/UABEA) can modify it.

**Comment by K0lb3** [comment] 2021-12-11 22:43
Thanks for reporting the issue.
Apparently the SerializedFile within the BundleFIle you provided says that it's version is 0.0.0,
which is obviously wrong.
I tried replacing it with the version engine of the BundleFile which worked out fine,
so I will use this as hotfix for now.

**Comment by CCTV-1** [comment] 2021-12-12 00:58
now UnityPy can modify it. but game can't load modified resource file.

code like:
```Python3
import UnityPy

env = UnityPy.load("demo.res")

for obj in env.objects:
    if obj.type.name == "Texture2D":
        if obj.container.endswith("_AIF.tga"):
            objData = obj.read()
            pil_img = Image.open('410991.png')
            objData.image = pil_img
            objData.save()
with open('modify.res', 'wb') as f:
    f.write(env.file.save())
```

game log:
```
[1599] [Assets] Couldnt find asset Assets/Core/CardArt/410000/410991_AIF.tga
[1637] Failed to load 'archive:/CAB-2041ce525f12ac0d28f0af070532cc04/CAB-UnityPy_Mod.resS'. File may be corrupted or was serialized with a newer version of Unity.
[1637] The AssetBundle 'MTGA_Data\Downloads\AssetBundle\410991_CardArt_06e50a39-5ef06e249698832ea391293b96c752d3.mtga' can't be loaded because it was not built with the right version or build target.
```

if use [UABEA](https://github.com/nesrak1/UABEA) modify,game can load modified resource file.

[raw res.zip](https://github.com/K0lb3/UnityPy/files/7697958/raw.res.zip)
[UABEA Modify.zip](https://github.com/K0lb3/UnityPy/files/7697959/UABEA.Modify.zip)
[UnityPy Modify.zip](https://github.com/K0lb3/UnityPy/files/7697960/UnityPy.Modify.zip)

I guess the game(or Unity) expect SerializedFile keep 0.0.0?

**Comment by K0lb3** [comment] 2021-12-12 21:22
That's quite likely.
Fixing the issue won't be hard,
I just didn't think about it beforehand because I was a bit too sleepy at the time I fixed it.
Another problem might be that the replaced texture is stored within a new cab,
so if it still doesn't work after the update, try to use

set_image instead of .image=

e.g.
```python
import UnityPy

env = UnityPy.load("demo.res")

for obj in env.objects:
    if obj.type.name == "Texture2D":
        if obj.container.endswith("_AIF.tga"):
            objData = obj.read()
            pil_img = Image.open('410991.png')
            objData.set_image(img = pil_img, in_cab = False)
            objData.save()
with open('modify.res', 'wb') as f:
    f.write(env.file.save())
    ```

to force UnityPy to store the texture data within the object instead of within a new resource file.

**Comment by CCTV-1** [comment] 2021-12-13 01:25
after update

use `.image =` will create a invalid file.([AssetStudio](https://github.com/Perfare/AssetStudio) can't read the image)
AssetStudio log:
```
Preview Texture2D:410991_AIF error
Can't find the resource file CAB-UnityPy_Mod.resS
    at ...call stack...
```

use 'set_image' function will create a correct file([AssetStudio](https://github.com/Perfare/AssetStudio) can read the image)

if call `env.file.save(packer="lz4")`, neither file game can load.

if call `env.file.save()`. file generated from 'set_image' can be game load,but cardview have some problems.
![1](https://user-images.githubusercontent.com/7350506/145736760-c53123e2-ba3e-4092-9e32-951e60f1f0e0.png)
![2](https://user-images.githubusercontent.com/7350506/145736770-57e66393-909a-40f2-ac61-963c2c05051d.png)

**Comment by K0lb3** [comment] 2021-12-16 14:52
I guess that the issue could be related to the texture compression.
Since you already mentioned UABEAvalonia, have you tried it with it as well?
And if so, does it produce the same issue or does the miniature look fine with it?

**Comment by CCTV-1** [comment] 2021-12-17 01:07
> I guess that the issue could be related to the texture compression. Since you already mentioned UABEAvalonia, have you tried it with it as well? And if so, does it produce the same issue or does the miniature look fine with it?

the files generated by UABEAvalonia are normal.(LZ4 and LZMA and no compress).
and if i use UnityPy replace TextAsset,also can not call `env.file.save(packer="lz4")`,can only call `env.file.save()`.otherwise the game will not load modified resources.

**Comment by K0lb3** [comment] 2022-01-03 00:38
I meant, is the cardview fine with UABEAvalonia?
If that's the case I will have to check how they recompress the texture to adjust it in UnityPy.

**Comment by CCTV-1** [comment] 2022-01-03 01:43
> I meant, is the cardview fine with UABEAvalonia? If that's the case I will have to check how they recompress the texture to adjust it in UnityPy.

cardview  is normal(with UABEAvalonia)

**Comment by K0lb3** [comment] 2022-01-28 22:09
I've come back to the issue today and noticed that the problem is caused by the tool used for the BC/DXT compression.
Its result is way smaller than the original.

I'm currently working on fix for the issue -  so making ISPC_TEXCOMP builds for all major versions.
Unity itself uses it, and well, UABEAvalonia as well, but it lacks builds for MacOS and arm.

**Comment by K0lb3** [comment] 2022-01-28 23:11
A small correction.
Thanks to a mention of the discord user [[nope]] the issue could be found.
The problem is caused by the mip maps count.
When replacing the texture UnityPy will only store one map, but didn't change the mipcount so far.
UABEAvalonia sets the mipcount to 1 after a replacement,
but that could negatively affect the performance.

I tested some textures with mipmaps just now and noticed that the data of the various mipmaps is simply appended to a big blob containing the data of all mipmaps. So UnityPy will have to do just that as well, creating small versions of the original image and joining the data of all of them together to one big blob.
While this definitely produces bigger texture files, it should be safer in terms of performance and compatibility.

**Comment by K0lb3** [comment] 2022-01-28 23:50
I pushed a fix for the issue just now.
UnityPy will now set the mipmap count by default to one if a texture is replaced.
If it affects the performance too much, mipmaps can be kept by using the set_image function,
which now offers the mipmap_count as kwarg and generates mipmaps according to the input.
(if the input is too big, it will be automatically adjusted)

**Comment by CCTV-1** [comment] 2022-01-29 02:12
after updating to 1.7.31,the CardView normal now.

**Closed** 2022-01-29 02:12 UTC
Labels: bug
